# Name of loaded config, to show to user
name = "exFat filesystem driver"

# Drivers this driver depends on (config file must exist)
#depends = ["i_bdm"]

# Modules to load in load environment
[[module]]
file = "bdmfs_fatfs.irx"
env = ["LE"]

# Modules to load in emulation environment
[[module]]
file = "fhi_bd_defrag.irx"
func = "FHI_BD_DEFRAG"
env = ["EE"]
