# Name of loaded config, to show to user
name = "Block Device Manager"

# Modules to load in load environment
[[module]]
file = "bdm.irx"
env = ["LE"]
[[module]]
file = "iomanX.irx"
env = ["LE"]
[[module]]
file = "fileXio.irx"
env = ["LE"]
