site_name: PS2 Homebrew Store
site_url: https://ps2homebrewstore.com

theme:
  name: material
  custom_dir: overrides
  language: en 
  logo: assets/logo.png
  # icon:
  #   logo: material/store
  favicon: assets/logo.png
  # logo: assets/logo.png
  font:
    text: Oxanium
    code: Roboto Mono
  palette: 
    # Palette toggle for light mode
    - scheme: default
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        
    # Palette toggle for dark mode
    - scheme: slate
      accent: indigo
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  features:
    - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    # - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - toc.follow
    # - toc.integrate


# Content width
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mermaid.mjs

plugins:
  - search
  - blog
  - glightbox:
      manual: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - footnotes
  - abbr
  - meta

watch:
  - includes
  
extra:
  alternate:
  # - name: English
  #   link: /en/ 
  #   lang: en
  # - name: Deutsch
  #   link: /de/
  #   lang: de
  # - name: French
  #   link: /fr/
  #   lang: fr
  # - name: Spanish
  #   link: /es/
  #   lang: es
  social:
    - icon: fontawesome/brands/discord
      name: PS2 Space on Discord
      link: https://discord.gg/r3frDccRby
    - icon: fontawesome/brands/github
      name: PS2 Homebrew Store on GitHub
      link: https://github.com/saildot4k/ps2homebrewstore

# Page tree
nav:
  - Home: index.md
    
  - Exploits: exploits/index.md

  - Loaders: loaders/index.md

  - Apps: apps/index.md

  - System Apps: sys_apps/index.md

  - Emulators: emulators/index.md

  - Games: games/index.md

  - Diagnostics: diag/index.md

  - UMCS: umcs/index.md

  - PC Tools: pc-tools/index.md

  - Thanks: thanks/index.md




    