# Name of loaded config, to show to user
name = "MX4SIO in MC2 BDM driver"

# Drivers this driver depends on (config file must exist)
depends = ["i_bdm"]

# Modules to load
[[module]]
file = "mx4sio_bd_mini.irx"
env = ["LE", "EE"]
