# Name of loaded config, to show to user
name = "ATA emulation using image file"

# Modules to load
[[module]]
file = "atad_emu.irx"
env = ["EE"]

# Modules of the game that are faked/blocked
[[fake]]
file = "ATAD.IRX"
name = "atad_driver"
version = 0x0207
startrv = 0 # 0=RESIDENT_END, 1=NO_RESIDENT_END, 2=REMOVABLE_END

# For booting rom0:OSDSYS, block the following?:
# - rom0:ATAD (dev9 + atad combined driver)
# - HDDLOAD
#
# What do these libraries do? Also block?:
# - rom0:XDEV9 ?
# - rom0:XDEV9SERV ?
# - rom0:PS1ID ?
# - rom0:PS1VERE ?
# - rom1:DVDIDE ?
