# Name of loaded config, to show to user
name = "Patches for Ratchet Clank 3 / Up Your Arsenal - ONLINE!"

# For testing
#default_bsd = "ata"
#default_dvd = "mass:DVD/Ratchet Clank - Up Your Arsenal (U).iso"

# Boot directly into online menu
default_elf = "cdrom0:I5BOOTN.ELF;1"

# Load patch module that fixes a game bug
[[module]]
file = "patch_rc_uya.irx"
env = ["EE"]
