# Name of loaded config, to show to user
name = "Block Device Manager (with FHI)"

# Modules to load in load environment
[[module]]
file = "bdm.irx"
env = ["LE"]
# These 3 drivers are needed for isofs
# it would be nice if we could remove that dependency
[[module]]
file = "iomanX.irx"
env = ["LE"]
[[module]]
file = "fileXio.irx"
env = ["LE"]
[[module]]
file = "isofs.irx"
env = ["LE"]

# Modules to load in emulation environment
[[module]]
file = "fhi_bd_defrag.irx"
env = ["EE"]
