# Name of loaded config, to show to user
name = "System settings and drivers"

# Default argument values
# Overwrite these from the command line
default_bsd = "no"
default_bsdfs = "exfat"
default_dvd = "no"
#default_ata0 = "mass:mydrive0.bin"
#default_ata0id = "mass:mydrive0_id.bin"
#default_ata1 = "mass:mydrive1.bin"
#default_mc0 = "mass:mymc0.bin"
#default_mc1 = "mass:mymc1.bin"
default_elf = "auto"
#default_mt = "dvd"
#default_gc = "12"
#default_gsm = "fp"
#default_cfg = ""
default_dbc = false
default_logo = false

# EE_CORE configuration
eecore_elf = "ee_core.elf"
eecore_mod_base = 0x95000
#eecore_mod_base = 0xA7000

# Select the number of sectors for the FS buffer
# A small value can increase game compatibility
# A large value can increase performce
# Min=2, Max=128, Default=8
cdvdman_fs_sectors = 8

# Override the 8-byte string returned by:
# - sceCdRI
# This string is also used by:
# - sceCdReadGUID
# - sceCdReadModelID
#
# This string is used (for instance) by the sony network configuration
# to verify if the config belongs to the specific console.
#
#ilink_id = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

# Use the 5-byte string returned by:
# - sceCdReadDiskID
#disk_id = [0x00, 0x00, 0x00, 0x00, 0x00]

# Modules to load in emulation environment
[[module]]
file = "eesync.irx"
ioprp = "EESYNC"
env = ["EE"]
[[module]]
file = "imgdrv.irx"
func = "IMGDRV" # used by EECORE durion IOP reboot
env = ["EE"]
# By default the system rom0:UDNL will be used, but this can be overruled here
# Some games (like Auto Modellista) don't work over USB with the default UDNL.
[[module]]
file = "udnl.irx"
#file = "udnl-t300.irx"
func = "UDNL" # used by EECORE durion IOP reboot
env = ["EE"]
[[module]]
file = "fakemod.irx"
func = "FAKEMOD" # loaded last, so we don't fake our own modules
env = ["EE"]

#[[module]]
#file = "patch_freemem.irx"
#args = ["512", "X"] # "X" = block above limit (default no blocking), number is limit in KiB (default 512KiB)
#env = ["EE"]

#[[module]]
#file = "memcheck.irx"
#env = ["EE"]

#[[module]]
#file = "patch_membo.irx"
#env = ["EE"]

# It's best to load this module last (bottom of bsd-usb.toml for instance)
#[[module]]
#file = "gapfill.irx"
#env = ["EE"]
